MAC1 = "44:a8:bc:43:97:2d"
MAC2 = "00:04:4a:86:32:9b"
FAKE_MAC = "00:00:00:00:00:00"
MAC_GROUP_1 = "IPAD"
MAC_GROUP_2 = "ALL"
FAKE_IP_ADDR = "192.168.100.100"

DEFAULT_IKUAI_CLIENT_LIST_MONITOR_LANIP = {
    'total': 2,
    'data': [{'uptime': '2024-02-25 13:32:36',
              'mac': f'{MAC1}',
              'dtalk_name': '',
              'uprate': '',
              'link_addr': '',
              'bssid': '',
              'comment': 'iPad',
              'downrate': '',
              'reject': 0,
              'hostname': 'iPad',
              'apmac': '',
              'frequencies': '',
              'ssid': '',
              'apname': '',
              'ip_addr_int': 3232263691,
              'connect_num': 1,
              'upload': 0,
              'download': 0,
              'auth_type': 0,
              'client_type': 'Unknown',
              'client_device': 'Unknown',
              'timestamp': 1708839156,
              'id': 1,
              'ac_gid': 0,
              'webid': 0,
              'ppptype': '',
              'ip_addr': '192.168.110.11',
              'username': '',
              'total_up': 2387003,
              'total_down': 1913202,
              'signal': ''},
             {'uptime': '2024-02-25 13:32:55',
              'mac': MAC2,
              'dtalk_name': '',
              'uprate': '',
              'link_addr': '',
              'bssid': '',
              'comment': 'TVBOX',
              'downrate': '',
              'reject': 0,
              'hostname': 'TVBOX',
              'apmac': '',
              'frequencies': '',
              'ssid': '',
              'apname': '',
              'ip_addr_int': 3232263684,
              'connect_num': 1,
              'upload': 0,
              'download': 0,
              'auth_type': 0,
              'client_type': 'Unknown',
              'client_device': 'Xiaomi',
              'timestamp': 1708839175,
              'id': 2,
              'ac_gid': 0,
              'webid': 0,
              'ppptype': '',
              'ip_addr': '192.168.110.4',
              'username': '',
              'total_up': 2022282,
              'total_down': 2002042,
              'signal': ''}]}

DEFAULT_IKUAI_CLIENT_LIST_MAC_GROUPS = {
    'total': 2,
    'data': [{'group_name': f'{MAC_GROUP_1}',
              'addr_pool': f'{MAC1}',
              'id': 1,
              'comment': ''},
             {'group_name': MAC_GROUP_2,
              'addr_pool': f'{MAC2},{MAC1}',
              'id': 8,
              'comment': ''}]}

DEFAULT_IKUAI_CLIENT_LIST_ACL_L7 = {
    'total': 9,
    'data': [{'prio': 28,
              'action': 'drop',
              'app_proto': '所有协议',
              'src_addr': f"{MAC_GROUP_1},{FAKE_IP_ADDR}",
              'dst_addr': '',
              'week': '1234567',
              'time': '00:00-23:59',
              'id': 2,
              'enabled': 'yes',
              'comment': '阻断全部上网'},
             {'prio': 10,
              'action': 'accept',
              'app_proto': '所有协议',
              'src_addr': MAC_GROUP_1,
              'dst_addr': '',
              'week': '6',
              'time': '21:36-22:04',
              'id': 4,
              'enabled': 'no',
              'comment': 'ipad临时'},
             {'prio': 8,
              'action': 'drop',
              'app_proto': '网络游戏',
              'src_addr': MAC_GROUP_1,
              'dst_addr': '',
              'week': '1234567',
              'time': '00:00-23:59',
              'id': 5,
              'enabled': 'yes',
              'comment': '阻止游戏'},
             {'prio': 8,
              'action': 'drop',
              'app_proto': '网络视频',
              'src_addr': MAC_GROUP_1,
              'dst_addr': '',
              'week': '1234567',
              'time': '00:00-23:59',
              'id': 6,
              'enabled': 'yes',
              'comment': '阻止视频'},
             {'prio': 16,
              'action': 'drop',
              'app_proto': '国内视频',
              'src_addr': MAC_GROUP_2,
              'dst_addr': '',
              'week': '1234567',
              'time': '00:00-23:30',
              'id': 7,
              'enabled': 'yes',
              'comment': '阻止电视'},
             {'prio': 32,
              'action': 'drop',
              'app_proto': '淘宝视频,淘宝通用账号,淘宝',
              'src_addr': MAC_GROUP_2,
              'dst_addr': '',
              'week': '1234567',
              'time': '00:00-23:59',
              'id': 8,
              'enabled': 'yes',
              'comment': '禁止淘宝'},
             {'prio': 1,
              'action': 'accept',
              'app_proto': '所有协议',
              'src_addr': MAC_GROUP_2,
              'dst_addr': '',
              'week': '3',
              'time': '22:10-22:25',
              'id': 9,
              'enabled': 'yes',
              'comment': '允许电视'},
             {'prio': 15,
              'action': 'drop',
              'app_proto': '所有协议',
              'src_addr': MAC_GROUP_2,
              'dst_addr': '',
              'week': '1234567',
              'time': '00:00-23:59',
              'id': 10,
              'enabled': 'yes',
              'comment': '禁止电视'},
             {'prio': 2,
              'action': 'accept',
              'app_proto': '所有协议',
              'src_addr': MAC_GROUP_2,
              'dst_addr': '',
              'week': '1234567',
              'time': '00:00-05:00',
              'id': 11,
              'enabled': 'yes',
              'comment': '允许电视'}]}

DEFAULT_IKUAI_CLIENT_LIST_DOMAIN_BLACKLIST = {
    'total': 2,
    'data': [{'time': '00:00-23:59',
              'id': 1,
              'enabled': 'yes',
              'comment': '',
              'domain_group': '游戏网站',
              'weekdays': '12345',
              'ipaddr': f"{MAC_GROUP_1},{FAKE_IP_ADDR}"},
             {'time': '00:00-23:59',
              'id': 2,
              'enabled': 'no',
              'comment': '',
              'domain_group': '视频网站',
              'weekdays': '67',
              'ipaddr': MAC_GROUP_1}
             ]}

DEFAULT_IKUAI_CLIENT_LIST_URL_BLACK = {
    'total': 2,
    'data': [{'ip_addr': MAC_GROUP_1,
              'id': 1,
              'enabled': 'no',
              'week': '1234567',
              'comment': 'foo',
              'time': '00:00-23:59',
              'domain': 'foo.bar.com,bar.foo.com',
              'mode': 0},
             {'ip_addr': f"{MAC_GROUP_1},{FAKE_IP_ADDR}",
              'id': 2,
              'enabled': 'yes',
              'week': '1234567',
              'comment': 'bar',
              'time': '00:00-23:59',
              'domain': 'bar.com.foo,foo.com.bar',
              'mode': 0}
             ]}
