# Generated by Django 4.2.10 on 2024-02-18 08:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import my_router.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Router",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Router name")),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The admin URL of the router", unique=True
                    ),
                ),
                (
                    "admin_username",
                    models.CharField(
                        help_text="Admin username of the iKuai router",
                        max_length=255,
                        verbose_name="Admin username",
                    ),
                ),
                (
                    "admin_password",
                    models.CharField(
                        help_text="Admin password of the iKuai router",
                        max_length=255,
                        verbose_name="Admin password",
                    ),
                ),
                (
                    "ikuai_version",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="iKuai version"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("disabled", "Disabled")],
                        default="active",
                        help_text="This determines whether remote information will be fetched periodically",
                        max_length=50,
                        verbose_name="Router status",
                    ),
                ),
                (
                    "fetch_interval",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="The interval of the app to fetch the information on the router, in seconds",
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Fetch interval",
                    ),
                ),
                (
                    "task",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="django_celery_beat.periodictask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Router",
                "verbose_name_plural": "Routers",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=31, null=True, verbose_name="Device name"
                    ),
                ),
                (
                    "mac",
                    my_router.fields.MACAddressField(
                        db_index=True, max_length=17, verbose_name="MAC address"
                    ),
                ),
                (
                    "known",
                    models.BooleanField(
                        default=False,
                        help_text="This devices is known.",
                        verbose_name="Known device",
                    ),
                ),
                (
                    "ignore",
                    models.BooleanField(
                        default=False,
                        help_text="This device will be ignored when listing and bulk applying constraints.",
                        verbose_name="Ignored device",
                    ),
                ),
                (
                    "added_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Added datetime"
                    ),
                ),
                (
                    "router",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="my_router.router",
                        verbose_name="Router connected",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device",
                "verbose_name_plural": "Devices",
                "ordering": ("-added_datetime",),
                "unique_together": {("router", "mac")},
            },
        ),
    ]
