# Generated by Django 4.2.10 on 2024-02-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_router", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="name",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Device name"
            ),
        ),
    ]
