# Generated by Django 4.2.10 on 2024-02-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_router", "0002_alter_device_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="block_mac_by_proto_ctrl",
            field=models.BooleanField(
                default=False,
                help_text="Banning all protocols in acl_l7 will result in MAC blocking",
                verbose_name="Control MAC via Proto Ctrl",
            ),
        ),
    ]
